version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - .env
    volumes:
      - ./backend/data:/app/data

  static-server:
    build:
      context: .
      dockerfile: ./static_server/Dockerfile
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - VITE_API_URL=http://${BACKEND_URL}:${BACKEND_PORT}
    env_file:
      - .env
    depends_on:
      - backend 